version: "2"
services:
  webserver:
    environment:
      MOODLE_DOCKER_DBTYPE: mariadb
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
  db:
    image: mariadb:${MOODLE_DOCKER_DB_VERSION:-10.7}
    command: >
              --character-set-server=utf8mb4
              --collation-server=utf8mb4_bin
              --innodb_file_format=barracuda
              --innodb_file_per_table=On
              --wait-timeout=28800
    environment:
      MYSQL_ROOT_PASSWORD: "m@0dl3ing"
      MYSQL_USER: moodle
      MYSQL_PASSWORD: "m@0dl3ing"
      MYSQL_DATABASE: moodle
    volumes:
        - dbdata:/var/lib/mysql

  cron:
    image: alpine/curl:latest
    restart: "always"
    command: [ "/bin/sh", "-c", "while true; do sleep 5; curl -s 'http://webserver:80/admin/cron.php'; sleep 55; done" ]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8001:80

volumes:
  dbdata:
