version: "2"
services:
  webserver:
    container_name: ${COMPOSE_PROJECT_NAME}-webserver
    restart: "always"
    environment:
      MOODLE_DOCKER_DBTYPE: mariadb
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
      MOODLE_DOCKER_CLIENT_HOST_IP: ${MOODLE_DOCKER_CLIENT_HOST_IP}
      MOODLE_DOCKER_DBNAME: ${COMPOSE_PROJECT_NAME}
    volumes:
      - moodledata:/var/www/moodledata
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - "db"
    ports:
      - ${MOODLE_DOCKER_XDEBUG_PORT}:9003

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: mariadb:${MOODLE_DOCKER_DB_VERSION:-10.7}
    restart: "always"
    entrypoint: mysqld_safe --skip-grant-tables --user=mysql
    command: >
              --character-set-server=utf8mb4
              --collation-server=utf8mb4_bin
              --innodb_file_format=barracuda
              --innodb_file_per_table=On
              --wait-timeout=28800
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "m@0dl3ing"
      MYSQL_USER: moodle
      MYSQL_PASSWORD: "m@0dl3ing"
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes

  cron:
    container_name: ${COMPOSE_PROJECT_NAME}-cron
    image: alpine/curl:latest
    restart: "always"
    command: [ "/bin/sh", "-c", "while true; do sleep 5; curl -s 'http://webserver/admin/cron.php'; sleep 55; done" ]
    depends_on:
      - "webserver"

  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}-pma
    image: phpmyadmin/phpmyadmin
    restart: "always"
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: ${MOODLE_DOCKER_DB_PORT}
      PMA_ARBITRARY: 1
    ports:
      - 8900:80
    depends_on:
      - "db"

  keycloak:
    container_name: ${COMPOSE_PROJECT_NAME}-keycloak
    image: quay.io/keycloak/keycloak:latest
    # restart: "always"
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: moodle
      DB_PASSWORD: m@0dl3ing
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
    ports:
      - 8080:8080
    depends_on:
      - db

  mailhog:
    container_name: ${COMPOSE_PROJECT_NAME}-mailhog
    restart: "always"
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  moodleapp:
    container_name: ${COMPOSE_PROJECT_NAME}-moodleapp
    restart: "always"

  exttests:
    container_name: ${COMPOSE_PROJECT_NAME}-exttests

  selenium:
    container_name: ${COMPOSE_PROJECT_NAME}-selenium

volumes:
  moodledata:
  dbdata:
