version: "2"
services:
  webserver:
    restart: "always"
    environment:
      MOODLE_DOCKER_DBTYPE: mariadb
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
      MOODLE_DOCKER_CLIENT_HOST_IP: ${MOODLE_DOCKER_CLIENT_HOST_IP}
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - "db"

  db:
    image: mariadb:${MOODLE_DOCKER_DB_VERSION:-10.7}
    restart: "always"
    entrypoint: mysqld_safe --skip-grant-tables --user=mysql
    command: >
              --character-set-server=utf8mb4
              --collation-server=utf8mb4_bin
              --innodb_file_format=barracuda
              --innodb_file_per_table=On
              --wait-timeout=28800
    environment:
      MYSQL_ROOT_PASSWORD: "m@0dl3ing"
      MYSQL_USER: moodle
      MYSQL_PASSWORD: "m@0dl3ing"
      MYSQL_DATABASE: moodle
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes

  cron:
    image: alpine/curl:latest
    restart: "always"
    command: [ "/bin/sh", "-c", "while true; do sleep 5; curl -s 'http://webserver/admin/cron.php'; sleep 55; done" ]
    depends_on:
      - "webserver"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: "always"
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8900:80
    depends_on:
      - "db"
